version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
      commands:
        npm install
  post_build:
    commands:
      aws elasticbeanstalk update-environment --environment-name test-environment
